lint:
  actions_awsfulltest: false
  files_exist:
    - .github/workflows/ci.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: "@maxulysse"
  description: help community build references
  force: false
  is_nfcore: true
  name: references
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 1.0dev
