contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #references channel"
    url: https://nfcore.slack.com/channels/references
    about: Discussion about the nf-core/references pipeline
